# Site settings
url: "https://robwise.github.io" # the base hostname & protocol for your site
baseurl: ""                      # the subpath of your site, e.g. /blog/
permalink: :categories/:title
timezone: America/New_York

title: Rob Wise
description: Personal website and blog for Rob Wise (web developer).
email: robert.wise@outlook.com
twitter_username: RobAWise
github_username:  robwise
disqus_shortname: 'rob-wise'

keep_files: []
exclude: ["*.sublime-project",
          "*.sublime-workspace",
          "_app",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "LICENSE",
          "node_modules",
          "package.json",
          "README.md",
          "bower.json"]

# Markdown settings
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults (these are overridden if explicitly set in front matter)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Rob Wise"
      categories: blog
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      author: "Rob Wise"
      categories: blog
      layout: "post"
